### ISSUE TITLE
Does it work on 1.8.7 version?

### ISSUE THREAD

**Issue by guilhermemaranhao** [fnando/cpf_cnpj#11]
Olá,

Instalei a gem no meu projeto ruby de versão 1.8.7, mas a validação de CPF parece não estar funcionando, pois sempre retorna FALSE, independente do CPF ser válido ou não.
Devido a versão do ruby (1.8.7), eu tive que refatorar a classe CPF substituindo o symbol :strict por uma variável strict, caso contrário dava erro na gem.
Não sei se foi por essa causa, a validação sempre retorna erro. Sabe de alguma versão da gem compatível com o ruby 1.8.7 que eu poderia instalar?

Obrigado,

Guilherme

**Comment by guilhermemaranhao** [comment]
Olá,

Instalei a versão '0.1.0' e agora recebo o seguinte erro:

```
#Esse cpf 85434482476 é válido
cpf = CPF.new(85434482476)
cpf.valid?

```
```
NoMethodError: undefined method `with_index' for [8, 5, 4, 3, 4, 4, 8, 2, 4]:Array
	from /Users/guilherme/.rvm/gems/ruby-1.8.7-head@atena/gems/cpf_cnpj-0.1.0/lib/cpf/verifier_digit.rb:6:in `generate'
	from /Users/guilherme/.rvm/gems/ruby-1.8.7-head@atena/gems/cpf_cnpj-0.1.0/lib/cpf.rb:57:in `valid?'
	from (irb):4
```

**Comment by fnando** [comment]
É, versão 1.8.7 é dureza funcionar… quando lancei a gem o já devia estar na versão 2.0.0. Enfim, fazer funcionar até tem como; tem que ver os erros e substituir por código que funciona no 1.8.7, mas não recomendo fazer isso.
